### ISSUE TITLE
Grove-specific repository

### ISSUE THREAD

**Issue by kevin-brown** [zorg-framework/zorg-i2c#1]
This should probably be renamed to be a bit more specific to the Grove/Seed kits. Most of the commands, as well as the addresses used, are specific to the sensors that were included.

**Comment by gunthercox** [comment]
I believe this should be all set. Is there any drivers from the other module that you think should be migrated in here as well?

**Comment by kevin-brown** [comment]
Looks like this is all set, I don't think there are any drivers that need to be migrated from other modules.
